{% set version = "2.0.0" %}

package:
  name: priority
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/priority/priority-{{ version }}.tar.gz
  sha256: c965d54f1b8d0d0b19479db3924c7c36cf672dbf2aec92d43fbdaf4492ba18c0

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - priority

about:
  home: http://python-hyper.org/priority/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pure-Python implementation of the HTTP/2 priority tree

extra:
  recipe-maintainers:
    - ocefpaf
