{% set name = "priority" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/priority-{{ version }}.tar.gz
  sha256: c965d54f1b8d0d0b19479db3924c7c36cf672dbf2aec92d43fbdaf4492ba18c0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - priority
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python-hyper/priority/
  summary: A pure-Python implementation of the HTTP/2 priority tree
  dev_url: https://github.com/python-hyper/priority/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
