travis:
  secure:
    BINSTAR_TOKEN: AQbQY/pmunUvlTek4tTyb5jkJxGDQKitH9CgD+0jp80SWGhGzoW92Wzyhpcmica7Xxi9DELxJyLecCsPVneONRgunaQP31UjUruBM9wS/Y3scLa3TusydbxhqYXPTU73bZQF9BMnMDT5KOSDP2VEsbjnwA3b4RpD9IEVDMgfGhesB45lVPaRqrjiuHk+Oirh1IO4qSFETBJD9mgElYNItoLFErwigV2ve+fgz8zco0/aKgpO0glU4eu6hlU272tljERmQPtzt9yLV1yOzstixGXWzFTDk0DAubHrPppgkq012nHeYuyrvGa8s7FspJHHrigZ6DTZzP2Ezdw4HvFAat+Io9W2JUsx3WJdgRKexbT8dXGZlPxoZNEoW6tPL7tG82pattvneFZ6R5/mrI8relftvG1b9WQAdh9Ye6wzRZJxPo0WKdyQw8rJVRXnIt99MMUL9Cbl6pKauPtQgYTuAeTcA/i9yFA4OY+J6skAbjUkRohabyFoeA/HeZXie9N+o0uJNK2qBN/mN90AaEILDW6k9hFxwvSSL1/oPTLnNED14FB1C7BaRtuZXvfKY9qO6VrSknl7V4t3DPoKBRyU1gP5ooigSL7avCflWDG9yHCHyVcT3LNOE9RL05QZK2CIPZIN6iECsqhpOF08eUnLZsRwgfaDWUgwIrh1xEE6bMs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
