travis:
  secure:
    BINSTAR_TOKEN: i/MfbLL/XP4zCizCFXCgKgk6pWSWDlnORyfM+9dWmWwyxVT1jwzTYkEGflXbvhXCww053UYMn/3shKbP6tebGhfi7xaa3TJJEtHsdQlXWBhu7S8s2+lq3Fkj3GcQRC1RkGKhCMxUfweS7J4FrXXTKardYvu9gfI3lMeazunci55r7yuZIsETZgtaUDsm6CtqFsprZw4bda2UP1NJQG7eCGHvqW3gtFP4OGUItD0BsmvnzAJaG/75XDhtDJ45ZKUiHUQDL30Kc7XJD72YXKEGgEAQ+3izrOY8Hvy9KX1ovD3cTqhhrf7sL013Ki/uM5v/arwuh7as3lEZLII5GQ/2nwYBKLbfuNDrNRZG4YCn9Yq2dxMAGrblnoUfxh5gkazIuG9zWo7JSiScGxlZhpZd2W4e7Oi1NAwIcX07Nq2WZGBv3nD9elQMAXk7xF2s1V2SJ/OKYo90nkXYC4FN2oJ0j4f4XnsBv0DqexeHC1sblv/LT1XXqrwP62IX9mXo4qDYcOmkpTch1HggUWHCeJZdXdNH1a9terfTgoscxmgtE5CC+c7AmcQ5CLJ2DHR1bAzm/jPn8ntJzKVy+qH9vPTrBPFW8cK82kLmxn4uzbRhLxEYuzdnNTZb3PEbes3RGYheC0xypID5H64TQgvRaOsHR4x0lsh4LtIuoIsgRlRyQxI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
